import { describe, it, expect } from "vitest";
import {
	dropKey,
	normalizeEmail,
	normalizePhone,
	sha256Base64,
} from "../worker/drop-normalize";

/**
 * Conformance vectors, generated by running the VIEW's own SQL over these
 * inputs — not by reading the spec and working out what it ought to produce.
 *
 *   email  base64Encode(SHA256(lowerUTF8(replaceRegexpAll(v, '\s', ''))))
 *   phone  base64Encode(SHA256(right(replaceRegexpAll(v, '[^0-9]', ''), 10)))
 *
 * That is the point of them. The gate and Cron C implement the same rules in
 * two languages, and if they drift nothing errors: the gate answers "not
 * listed" for someone Cron C would have matched, and a consumer quietly stops
 * being suppressed. These turn that silent divergence into a red test.
 *
 * To regenerate, run those two expressions in ClickHouse over the same inputs.
 */
const VECTORS: { type: "email" | "phone"; raw: string; normalized: string; hash: string }[] = [
	// the country code is dropped by taking the LAST ten digits
	{
		type: "phone",
		raw: "+12012000776",
		normalized: "2012000776",
		hash: "4UenbPXYEBN8GcJjHxXMvyl+k7Kn7ga36tuyywlA7dA=",
	},
	// the spec's own example
	{
		type: "phone",
		raw: "+1(415)555-9317",
		normalized: "4155559317",
		hash: "vGM7y5n+hBXRSEAklhHDPCbysyNgYTmXdMcagGUOY8E=",
	},
	// formatting is irrelevant once the non-digits are gone
	{
		type: "phone",
		raw: "415 555 9317",
		normalized: "4155559317",
		hash: "vGM7y5n+hBXRSEAklhHDPCbysyNgYTmXdMcagGUOY8E=",
	},
	// an extension adds digits, so the ten-digit window shifts and the
	// identifier changes. Surprising, but it is what the spec says and what
	// the SQL does — the two agreeing matters more than either being cleverer.
	{
		type: "phone",
		raw: "(201) 200-0776 ext. 4",
		normalized: "0120007764",
		hash: "/Mw8w+HkA0q6LGZKJ/cO4RmeheJv9nggyoZJhazFzKU=",
	},
	// "or all digits if fewer than 10 are present"
	{
		type: "phone",
		raw: "5551234",
		normalized: "5551234",
		hash: "CHtw3FRxBkeA12yCbd8su+qwrVeGkrgztMk9suBFs4s=",
	},
	// non-NANP numbers get the same treatment, sensible or not
	{
		type: "phone",
		raw: "+44 20 7946 0958",
		normalized: "2079460958",
		hash: "ypaPFHTCsrHJobFT/xMWP1TvZTAFRK+RP1kfEc1NgLE=",
	},
	// the spec's own example
	{
		type: "email",
		raw: "Anna.Smith@Domain.com",
		normalized: "anna.smith@domain.com",
		hash: "KA18MT/ph6IHYjzT9zwETySDQyvSh87YuoSBpOQtkhE=",
	},
	{
		type: "email",
		raw: "  Foo@Bar.COM  ",
		normalized: "foo@bar.com",
		hash: "DH5qQFhi5ALrdqcPiib8cy0Hwykx6frpqxWCkR0uijs=",
	},
	// whitespace goes from the middle too, not only the ends
	{
		type: "email",
		raw: "a b c@example.com",
		normalized: "abc@example.com",
		hash: "ns6xNIPX8YfsAU/W1IVNFCDPxjQyivhfUdAyO6hiLiE=",
	},
	// dots and plus signs are KEPT. To a mail server user+tag@ may be the same
	// inbox; to DROP it is a different identifier, and collapsing it here
	// would suppress someone who is not on the list.
	{
		type: "email",
		raw: "user+tag@example.com",
		normalized: "user+tag@example.com",
		hash: "gOmq+yQL6LFY9VRVx7BWrEjRy5/k0L1+JE4PJlR9fc4=",
	},
	// non-ASCII lowercases, and is NOT transliterated — that mapping applies
	// to names in NDZ/NameVIN keys, not to e-mail addresses
	{
		type: "email",
		raw: "ÄÖÜ@Example.COM",
		normalized: "äöü@example.com",
		hash: "eDYYwrSID3iP1ayHW/nB4bYf3NRpy+RB4EReJSfq5SA=",
	},
];

describe("DROP normalization matches the ClickHouse view", () => {
	for (const v of VECTORS) {
		it(`${v.type}: ${JSON.stringify(v.raw)} -> ${JSON.stringify(v.normalized)}`, async () => {
			const got = await dropKey(v.type, v.raw);
			expect(got.normalized).toBe(v.normalized);
			expect(got.hash).toBe(v.hash);
		});
	}
});

describe("edge cases", () => {
	it("produces a 44-character Base64 digest", async () => {
		const h = await sha256Base64("anything");
		expect(h).toHaveLength(44);
		expect(h.endsWith("=")).toBe(true);
	});

	it("matches the known SHA-256 of the empty string", async () => {
		// Independent of the view: the published SHA-256 of "" in Base64.
		expect(await sha256Base64("")).toBe("47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=");
	});

	it("leaves a phone with no digits empty, rather than hashing nothing", () => {
		// The endpoint checks for this and answers before reaching KV, so an
		// unparseable input cannot collide with the hash of "".
		expect(normalizePhone("no digits here")).toBe("");
		expect(normalizeEmail("   ")).toBe("");
	});

	it("takes the last ten digits, not the first", () => {
		// The whole reason a country code disappears.
		expect(normalizePhone("1234567890123")).toBe("4567890123");
	});
});
